export const initialCategories = [
  {
    name: "Chuột Gaming",
    slug: "chuot-gaming",
    description: "Chuột chơi game không dây và có dây siêu nhẹ, cảm biến quang học chính xác cao.",
    imageUrl: "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?q=80&w=800&auto=format&fit=crop",
    orderIndex: 1,
  },
  {
    name: "Bàn phím cơ",
    slug: "ban-phim-co",
    description: "Bàn phím cơ custom, gaming phím cơ không dây, hotswap switch và keycap PBT cao cấp.",
    imageUrl: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?q=80&w=800&auto=format&fit=crop",
    orderIndex: 2,
  },
  {
    name: "Tai nghe & Audio",
    slug: "tai-nghe-audio",
    description: "Tai nghe gaming âm thanh vòm 7.1, mic lọc ồn đàm thoại rõ nét và loa để bàn.",
    imageUrl: "https://images.unsplash.com/photo-1546435770-a3e426bf472b?q=80&w=800&auto=format&fit=crop",
    orderIndex: 3,
  },
  {
    name: "Lót chuột & Mousepad",
    slug: "lot-chuot-mousepad",
    description: "Bàn di chuột speed/control, mousepad kính cường lực và lót chuột gaming chuyên nghiệp.",
    imageUrl: "https://images.unsplash.com/photo-1629429408209-1f912961dbd8?q=80&w=800&auto=format&fit=crop",
    orderIndex: 4,
  },
  {
    name: "Màn hình & Giá đỡ",
    slug: "man-hinh-gia-do",
    description: "Màn hình gaming tần số quét cao 144Hz - 360Hz, OLED và giá treo tay đỡ Arm kim loại.",
    imageUrl: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?q=80&w=800&auto=format&fit=crop",
    orderIndex: 5,
  },
  {
    name: "Phụ kiện & Switch",
    slug: "phu-kien-switch",
    description: "Switch cơ bôi trơn sẵn, dầu lube Krytox, keycap cherry profile và dây cáp xoắn bện dù.",
    imageUrl: "https://images.unsplash.com/photo-1595225476474-87563907a212?q=80&w=800&auto=format&fit=crop",
    orderIndex: 6,
  },
];

export const initialProducts = [
  // 1. Chuột Gaming
  {
    name: "Logitech G Pro X Superlight 2 Wireless",
    slug: "logitech-g-pro-x-superlight-2-wireless",
    categorySlug: "chuot-gaming",
    price: 3490000,
    originalPrice: 3990000,
    description: "Chuột thi đấu eSports đỉnh cao thế hệ mới, trang bị cảm biến HERO 2 độ phân giải lên đến 32.000 DPI, tần số phản hồi 2000Hz, switch lai quang học LIGHTFORCE và trọng lượng siêu nhẹ chỉ 60g.",
    images: [
      "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1626218174358-7769486c4b79?q=80&w=800&auto=format&fit=crop",
    ],
    specs: {
      "Cảm biến": "HERO 2 (32.000 DPI)",
      "Tần số phản hồi": "2.000Hz (Polling Rate)",
      "Trọng lượng": "60g",
      "Switch": "LIGHTFORCE Hybrid Optical-Mechanical",
      "Thời lượng pin": "95 giờ liên tục",
      "Kết nối": "Không dây LIGHTSPEED & Cáp USB-C",
    },
    inStock: true,
    isFeatured: true,
    isNew: true,
  },
  {
    name: "Razer DeathAdder V3 Pro Wireless White",
    slug: "razer-deathadder-v3-pro-wireless-white",
    categorySlug: "chuot-gaming",
    price: 3190000,
    originalPrice: 3690000,
    description: "Biểu tượng chuột công thái học cho game thủ thuận tay phải. Cảm biến Focus Pro 30K Optical Sensor, switch quang học Gen-3 90 triệu lần nhấn, form cầm ôm tay hoàn hảo cho game FPS/MOBA.",
    images: [
      "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?q=80&w=800&auto=format&fit=crop",
    ],
    specs: {
      "Cảm biến": "Focus Pro 30K Optical",
      "Độ phân giải": "30.000 DPI",
      "Trọng lượng": "63g",
      "Switch": "Razer Optical Gen-3",
      "Thời lượng pin": "90 giờ",
      "Kết nối": "Razer HyperSpeed Wireless / Type-C",
    },
    inStock: true,
    isFeatured: true,
    isNew: false,
  },
  {
    name: "Pulsar X2V2 Wireless Mini Gaming Mouse",
    slug: "pulsar-x2v2-wireless-mini-gaming-mouse",
    categorySlug: "chuot-gaming",
    price: 2190000,
    originalPrice: 2490000,
    description: "Chuột đối xứng siêu nhẹ cho form tay vừa và nhỏ, trang bị cảm biến PAW3395 hàng đầu, con lăn Pulsar Blue encoder chống bụi và thiết kế liền khối không lỗ chắc chắn.",
    images: [
      "https://images.unsplash.com/photo-1629429408209-1f912961dbd8?q=80&w=800&auto=format&fit=crop",
    ],
    specs: {
      "Cảm biến": "PixArt PAW3395",
      "Độ phân giải": "26.000 DPI",
      "Trọng lượng": "51g",
      "Switch": "Optical Switches",
      "Thời lượng pin": "100 giờ",
      "Kết nối": "2.4GHz Wireless / Type-C",
    },
    inStock: true,
    isFeatured: false,
    isNew: true,
  },

  // 2. Bàn phím cơ
  {
    name: "Keychron Q1 Pro Wireless Custom Mechanical Keyboard",
    slug: "keychron-q1-pro-wireless-custom-keyboard",
    categorySlug: "ban-phim-co",
    price: 4450000,
    originalPrice: 4950000,
    description: "Bàn phím cơ layout 75% vỏ nhôm CNC nguyên khối anodized, cấu trúc Double-Gasket êm ái, kết nối Bluetooth 5.1 và dây Type-C, núm xoay Rotary Encoder đa năng và tương thích QMK/VIA.",
    images: [
      "https://images.unsplash.com/photo-1587829741301-dc798b83add3?q=80&w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1595225476474-87563907a212?q=80&w=800&auto=format&fit=crop",
    ],
    specs: {
      "Layout": "75% (81 phím + núm xoay)",
      "Vỏ": "Nhôm CNC 6063",
      "Mạch": "Hotswap xuôi 5-pin RGB",
      "Mount": "Double-Gasket Mount",
      "Kết nối": "Bluetooth 5.1 / Type-C",
      "Switch": "Keychron K Pro Red / Brown",
      "Keycap": "KSA double-shot PBT",
    },
    inStock: true,
    isFeatured: true,
    isNew: true,
  },
  {
    name: "Akko 5075B Plus Dracula Castle Wireless",
    slug: "akko-5075b-plus-dracula-castle-wireless",
    categorySlug: "ban-phim-co",
    price: 1890000,
    originalPrice: 2190000,
    description: "Bàn phím cơ 3 chế độ kết nối (2.4GHz / Bluetooth 5.0 / USB-C), cấu trúc Gasket mount lót sẵn đầy đủ foam poron tiêu âm, dải LED viền RGB nổi bật và keycap PBT chất lượng cao.",
    images: [
      "https://images.unsplash.com/photo-1541140532154-b024d705b909?q=80&w=800&auto=format&fit=crop",
    ],
    specs: {
      "Layout": "75% (82 phím + núm xoay)",
      "Kết nối": "3 Mode (Dây / 2.4G / BT5.0)",
      "Switch": "Akko V3 Cream Yellow Pro",
      "Pin": "3000 mAh",
      "Đèn LED": "RGB 16.8 triệu màu + LED viền",
    },
    inStock: true,
    isFeatured: false,
    isNew: true,
  },
  {
    name: "MonsGeek M1 V3 QMK Hotswap Kit",
    slug: "monsgeek-m1-v3-qmk-hotswap-kit",
    categorySlug: "ban-phim-co",
    price: 1950000,
    originalPrice: null,
    description: "Kit bàn phím cơ nhôm quốc dân layout 75%, phiên bản V3 nâng cấp mạch xuôi hotswap, plate PC, núm xoay kim loại và đầy đủ bộ phụ kiện tape mod, stab plate mount đi kèm.",
    images: [
      "https://images.unsplash.com/photo-1595225476474-87563907a212?q=80&w=800&auto=format&fit=crop",
    ],
    specs: {
      "Chất liệu": "Nhôm CNC",
      "Layout": "75%",
      "Mạch": "Hotswap mạch xuôi 5-pin",
      "Kết nối": "Type-C có dây",
      "Phần mềm": "QMK / VIA",
    },
    inStock: true,
    isFeatured: true,
    isNew: false,
  },

  // 3. Tai nghe & Audio
  {
    name: "HyperX Cloud II Wireless Gaming Headset",
    slug: "hyperx-cloud-ii-wireless-gaming-headset",
    categorySlug: "tai-nghe-audio",
    price: 2790000,
    originalPrice: 3290000,
    description: "Chiếc tai nghe huyền thoại được nâng cấp không dây 2.4GHz không độ trễ, củ loa 53mm tái tạo âm trường chi tiết và đệm tai bọc mút hoạt tính êm ái trứ danh của dòng HyperX Cloud.",
    images: [
      "https://images.unsplash.com/photo-1546435770-a3e426bf472b?q=80&w=800&auto=format&fit=crop",
    ],
    specs: {
      "Củ loa": "Dynamic, 53mm nam châm đất hiếm",
      "Âm thanh": "Âm thanh vòm 7.1 ảo",
      "Thời lượng pin": "Lên tới 30 giờ",
      "Kết nối": "Không dây 2.4GHz USB Dongle",
      "Microphone": "Khử ồn có thể tháo rời",
    },
    inStock: true,
    isFeatured: true,
    isNew: false,
  },
  {
    name: "SteelSeries Arctis Nova 7 Wireless",
    slug: "steelseries-arctis-nova-7-wireless",
    categorySlug: "tai-nghe-audio",
    price: 4390000,
    originalPrice: 4890000,
    description: "Hệ thống âm thanh Nova Acoustic System kết hợp driver High Fidelity, tính năng kết nối đồng thời cả 2.4GHz và Bluetooth giúp vừa chơi game PC vừa nghe gọi điện thoại.",
    images: [
      "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=800&auto=format&fit=crop",
    ],
    specs: {
      "Driver": "40mm Neodymium",
      "Kết nối đồng thời": "2.4GHz + Bluetooth",
      "Thời lượng pin": "38 giờ (sạc nhanh 15 phút nghe 6 giờ)",
      "Microphone": "ClearCast Gen 2 khử ồn bằng AI",
    },
    inStock: true,
    isFeatured: false,
    isNew: true,
  },
  {
    name: "Razer BlackShark V2 Pro 2023 Edition",
    slug: "razer-blackshark-v2-pro-2023-edition",
    categorySlug: "tai-nghe-audio",
    price: 4890000,
    originalPrice: 5490000,
    description: "Phiên bản nâng cấp 2023 dành cho tuyển thủ chuyên nghiệp: Micro Razer HyperClear Super Wideband tái hiện giọng nói như phòng thu, củ loa TriForce Titanium 50mm và pin khủng tới 70 giờ.",
    images: [
      "https://images.unsplash.com/photo-1484704849700-f032a568e944?q=80&w=800&auto=format&fit=crop",
    ],
    specs: {
      "Driver": "Razer TriForce Titanium 50mm",
      "Microphone": "HyperClear Super Wideband 9.9mm",
      "Thời lượng pin": "70 giờ",
      "Trọng lượng": "320g",
      "Kết nối": "Razer HyperSpeed Wireless / BT 5.2",
    },
    inStock: true,
    isFeatured: true,
    isNew: true,
  },

  // 4. Lót chuột & Mousepad
  {
    name: "Artisan Ninja FX Zero XSoft Black",
    slug: "artisan-ninja-fx-zero-xsoft-black",
    categorySlug: "lot-chuot-mousepad",
    price: 1350000,
    originalPrice: null,
    description: "Tấm lót chuột cao cấp sản xuất 100% tại Nhật Bản. Bề mặt vải dệt đặc biệt cho độ kiểm soát hoàn hảo (control pad), đế bọt biển XSoft bám chặt mặt bàn không trượt một milimet.",
    images: [
      "https://images.unsplash.com/photo-1629429408209-1f912961dbd8?q=80&w=800&auto=format&fit=crop",
    ],
    specs: {
      "Xuất xứ": "Made in Japan",
      "Bề mặt": "Cloth Control (Vải dệt cao cấp)",
      "Độ dày": "4mm (Đế XSoft)",
      "Kích thước": "Size XL (490 x 420 mm)",
      "Bo viền": "Viền vắt sổ thấp hơn bề mặt",
    },
    inStock: true,
    isFeatured: true,
    isNew: false,
  },
  {
    name: "SteelSeries QcK Heavy XXL (900x400x4mm)",
    slug: "steelseries-qck-heavy-xxl",
    categorySlug: "lot-chuot-mousepad",
    price: 890000,
    originalPrice: 990000,
    description: "Lót chuột size lớn trải trọn bàn làm việc, bề mặt vải vi sợi độc quyền tối ưu độ chính xác tracking cho cả chuột quang và laser, độ dày 4mm êm ái cho cổ tay khi chơi game lâu.",
    images: [
      "https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=800&auto=format&fit=crop",
    ],
    specs: {
      "Kích thước": "900 x 400 mm (Size XXL)",
      "Độ dày": "4mm",
      "Chất liệu bề mặt": "Vải vi sợi dệt mật độ cao",
      "Đế": "Cao su tự nhiên chống trượt",
    },
    inStock: true,
    isFeatured: false,
    isNew: false,
  },
  {
    name: "Pulsar Superglide Glass Mousepad Red",
    slug: "pulsar-superglide-glass-mousepad-red",
    categorySlug: "lot-chuot-mousepad",
    price: 2490000,
    originalPrice: 2890000,
    description: "Bàn di chuột bằng kính cường lực Aluminosilicate siêu bền, bề mặt lướt nhanh như bay (speed) ma sát siêu thấp, độ bền vĩnh cửu không bị mòn vải và dễ dàng lau chùi.",
    images: [
      "https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=800&auto=format&fit=crop",
    ],
    specs: {
      "Chất liệu": "Kính cường lực Aluminosilicate",
      "Kích thước": "Size XL (490 x 420 x 4mm)",
      "Màu sắc": "Đỏ rực eSports",
      "Đế": "Silicone đúc khuôn bám dính toàn diện",
    },
    inStock: true,
    isFeatured: true,
    isNew: true,
  },

  // 5. Màn hình & Giá đỡ
  {
    name: "Asus ROG Swift OLED PG27AQDM 240Hz Gaming Monitor",
    slug: "asus-rog-swift-oled-pg27aqdm-gaming-monitor",
    categorySlug: "man-hinh-gia-do",
    price: 22990000,
    originalPrice: 24990000,
    description: "Màn hình gaming OLED 27 inch độ phân giải 2K QHD (2560x1440), tần số quét 240Hz, thời gian phản hồi siêu tốc 0.03ms, độ phủ màu 99% DCI-P3 cùng tản nhiệt buồng hơi độc quyền.",
    images: [
      "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?q=80&w=800&auto=format&fit=crop",
    ],
    specs: {
      "Kích thước": "26.5 inch OLED",
      "Độ phân giải": "2K QHD (2560 x 1440)",
      "Tần số quét": "240Hz",
      "Thời gian phản hồi": "0.03ms (GTG)",
      "Độ tương phản": "1.500.000:1",
      "Cổng kết nối": "HDMI 2.0, DisplayPort 1.4, USB Hub",
    },
    inStock: true,
    isFeatured: true,
    isNew: true,
  },
  {
    name: "Arm màn hình đôi Human Motion T6 Pro Dual",
    slug: "arm-man-hinh-doi-human-motion-t6-pro-dual",
    categorySlug: "man-hinh-gia-do",
    price: 1390000,
    originalPrice: 1690000,
    description: "Giá treo 2 màn hình trợ lực lò xo cơ khí Gas Spring chịu tải tới 9kg mỗi tay, hỗ trợ màn hình từ 17 đến 32 inch chuẩn VESA 75x75 và 100x100, điều chỉnh độ cao và góc xoay linh hoạt.",
    images: [
      "https://images.unsplash.com/photo-1593062096033-9a26b09da705?q=80&w=800&auto=format&fit=crop",
    ],
    specs: {
      "Số lượng tay nâng": "2 màn hình",
      "Tải trọng": "2kg - 9kg / mỗi tay",
      "Kích thước màn hỗ trợ": "17 inch - 32 inch",
      "Chuẩn VESA": "75x75mm & 100x100mm",
      "Lắp đặt": "Kẹp bàn hoặc khoan lỗ xuyên bàn",
    },
    inStock: true,
    isFeatured: false,
    isNew: false,
  },

  // 6. Phụ kiện & Switch
  {
    name: "Switch cơ Gateron Oil King Linear (Hộp 35 switch)",
    slug: "switch-co-gateron-oil-king-linear",
    categorySlug: "phu-kien-switch",
    price: 490000,
    originalPrice: null,
    description: "Dòng switch linear cao cấp được nhà máy lube sẵn cực kỳ mượt mà, thân vỏ nylon đen huyền bí cho âm thanh gõ trầm đục (thock) đã tai, lò xo 2 đoạn 55g đàn hồi nảy đều tay.",
    images: [
      "https://images.unsplash.com/photo-1595225476474-87563907a212?q=80&w=800&auto=format&fit=crop",
    ],
    specs: {
      "Loại switch": "Linear (5-pin)",
      "Lực nhấn kích hoạt": "55g",
      "Lực đáy": "65g",
      "Hành trình": "4.0mm",
      "Tình trạng lube": "Pre-lubed từ nhà máy",
      "Quy cách": "Hộp 35 switch",
    },
    inStock: true,
    isFeatured: true,
    isNew: false,
  },
  {
    name: "Dầu mỡ bôi trơn Switch & Stabilizer Krytox GPL 205g0 (5g)",
    slug: "dau-mo-boi-tron-krytox-gpl-205g0-5g",
    categorySlug: "phu-kien-switch",
    price: 150000,
    originalPrice: null,
    description: "Mỡ lube switch bàn phím cơ tiêu chuẩn vàng của giới chơi phím, nhập khẩu chính hãng Miller-Stephenson, giúp triệt tiêu tiếng sạn và ma sát khi gõ phím.",
    images: [
      "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=800&auto=format&fit=crop",
    ],
    specs: {
      "Dung tích": "Hũ 5g (Đủ lube khoảng 150 - 200 switch)",
      "Độ nhớt": "Grade 0 (mịn và đều)",
      "Ứng dụng": "Lube stem, housing switch linear và thanh stabilizer",
    },
    inStock: true,
    isFeatured: false,
    isNew: false,
  },
  {
    name: "Bộ Keycap PBT Cherry Profile GMK Minimal Clone (140 nút)",
    slug: "bo-keycap-pbt-cherry-profile-minimal",
    categorySlug: "phu-kien-switch",
    price: 550000,
    originalPrice: 650000,
    description: "Set keycap phối màu trắng đen tối giản Clean Tech, chất liệu PBT dày 1.5mm không bám vân tay hay bóng dầu theo thời gian, in nhiệt Dyesub sắc nét hỗ trợ hầu hết các layout bàn phím.",
    images: [
      "https://images.unsplash.com/photo-1587829741301-dc798b83add3?q=80&w=800&auto=format&fit=crop",
    ],
    specs: {
      "Chất liệu": "PBT Dyesub",
      "Profile": "Cherry Profile tiêu chuẩn",
      "Số nút": "140 phím",
      "Tương thích": "Layout 60, 65, 75, 87, 104, 108 phím",
    },
    inStock: true,
    isFeatured: false,
    isNew: true,
  },
];

export const initialBanners = [
  {
    title: "Logitech G Pro X Superlight 2 - Chuẩn mực thi đấu đỉnh cao",
    imageUrl: "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?q=80&w=1200&auto=format&fit=crop",
    linkUrl: "/products/logitech-g-pro-x-superlight-2-wireless",
    orderIndex: 1,
    isActive: true,
  },
  {
    title: "Keychron Q1 Pro - Đẳng cấp bàn phím cơ Custom nhôm CNC",
    imageUrl: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?q=80&w=1200&auto=format&fit=crop",
    linkUrl: "/products/keychron-q1-pro-wireless-custom-keyboard",
    orderIndex: 2,
    isActive: true,
  },
  {
    title: "Asus ROG Swift OLED 240Hz - Trải nghiệm hình ảnh chân thực",
    imageUrl: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?q=80&w=1200&auto=format&fit=crop",
    linkUrl: "/products/asus-rog-swift-oled-pg27aqdm-gaming-monitor",
    orderIndex: 3,
    isActive: true,
  },
];

export const initialSiteSettings = [
  { key: "shopName", value: "CaoTri Gaming Gear" },
  { key: "hotline", value: "0988.123.456" },
  { key: "zaloUrl", value: "https://zalo.me/0988123456" },
  { key: "facebookUrl", value: "https://facebook.com/caotrigear" },
  { key: "address", value: "Số 123 Đường Công Nghệ, Quận Cầu Giấy, TP. Hà Nội" },
  { key: "introText", value: "Chuyên cung cấp chuột gaming, bàn phím cơ, tai nghe máy tính chính hãng uy tín." },
];
